include /etc/nginx/geo/ruip.conf;

map $country $is_ru {
    default 0;
    RU 1;
}

server {
    listen 80;
    server_name _;

    set_real_ip_from 0.0.0.0/0;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    location = /stub {
        default_type text/plain;
        return 200 "HELLO KGB AGENT\n";
    }

    location / {
        if ($is_ru) {
            return 302 /stub;
        }

        proxy_pass http://fasapiapp:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
